version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Checking Python version..."
      - python --version || echo "Python not available in build environment"
      - echo "Repository URL: $ECR_REGISTRY"
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY:$IMAGE_TAG
      - echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REGISTRY:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '{"ImageURI":"%s"}' $ECR_REGISTRY:$IMAGE_TAG > imageDetail.json
      - echo "Image pushed successfully: $ECR_REGISTRY:$IMAGE_TAG"

artifacts:
  files:
    - imageDetail.json
  name: image_definition

cache:
  paths:
    - '/root/.cache/pip/**/*'